const data = [
    {
      id: 1,
      title: 'title',
      description: 'description',
      price: 1000,
    },
    { id: 2, title: 'title', description: 'fuck society', price: 1000 },
    { id: 3, title: 'title', description: 'fuck society', price: 1000 },
    { id: 4, title: 'title', description: 'fuck society', price: 1000 },
    { id: 5, title: 'title', description: 'fuck society', price: 1000 },
    { id: 6, title: 'title', description: 'fuck society', price: 1000 },
    { id: 7, title: 'title', description: 'fuck society', price: 1000 },
    { id: 8, title: 'title', description: 'fuck society', price: 1000 },
    { id: 9, title: 'title', description: 'fuck society', price: 1000 },
    { id: 10, title: 'title', description: 'fuck society', price: 1000 },
    { id: 11, title: 'title', description: 'fuck society', price: 1000 },
    { id: 12, title: 'title', description: 'fuck society', price: 1000 },
    { id: 13, title: 'title', description: 'fuck society', price: 1000 },
    { id: 14, title: 'title', description: 'fuck society', price: 1000 },
    { id: 15, title: 'title', description: 'fuck society', price: 1000 },
    { id: 16, title: 'title', description: 'fuck society', price: 1000 },
    { id: 17, title: 'title', description: 'fuck society', price: 1000 },
    { id: 18, title: 'title', description: 'fuck society', price: 1000 },
    { id: 19, title: 'title', description: 'fuck society', price: 1000 },
    { id: 20, title: 'title', description: 'fuck society', price: 1000 },
  ];